name: Auto-Build Custom n8n (External Browser)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Set to "true" to rebuild even if the image exists'
        required: false
        default: 'false'

permissions:
  contents: read
  packages: write


jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.tag_exists.outputs.exists }}
      n8n_tag: ${{ steps.find_tag.outputs.n8n_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Get digest of n8n:stable
        id: get_digest
        run: |
          digest=$(curl -s 'https://hub.docker.com/v2/repositories/n8nio/n8n/tags/stable' \
            | jq -r '.images[0].digest')
          echo "digest=$digest" >> "$GITHUB_OUTPUT"

      - name: Find matching version tag
        id: find_tag
        run: |
          digest="${{ steps.get_digest.outputs.digest }}"
          version=$(curl -s 'https://hub.docker.com/v2/repositories/n8nio/n8n/tags/?page_size=100' \
            | jq -r --arg digest "$digest" \
                '.results[] | select(.images[]?.digest == $digest) | .name' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -Vr | head -n 1)
          echo "n8n_tag=$version" >> "$GITHUB_OUTPUT"

      - name: Check if tag exists on GHCR
        id: tag_exists
        run: |
          TAG=${{ steps.find_tag.outputs.n8n_tag }}
          # 1. Get a pull-token for this repo
          GHCR_TOKEN=$(curl -s -u "mainto:${{ secrets.CR_PAT }}" \
            "https://ghcr.io/token?service=ghcr.io&scope=repository:${{ github.repository }}:pull" \
            | jq -r .token)

          # 2. Query the manifest using that token
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json" \
            -H "Authorization: Bearer $GHCR_TOKEN" \
            https://ghcr.io/v2/${{ github.repository }}/manifests/$TAG)
          echo "status=$STATUS"
          if [ "$STATUS" -eq 200 ]; then
            echo "exists=true"  >> "$GITHUB_OUTPUT"
          elif [ "$STATUS" -eq 403 ]; then
            exit 1 # Unauthorized
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.exists == 'false' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_build == 'true')
    steps:
      - uses: actions/checkout@v4

      - name: Print exists and tag
        run: |
          echo "Image exists: ${{ needs.check.outputs.exists }}"
          echo "n8n tag: ${{ needs.check.outputs.n8n_tag }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push custom n8n
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ needs.check.outputs.n8n_tag }}
            ghcr.io/${{ github.repository }}:latest
