name: Auto-Build Custom n8n (External Browser)

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [n8n_new_release]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Set to "true" to rebuild even if the image exists'
        required: false
        default: 'false'

permissions:
  contents: read
  packages: read


jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.tag_exists.outputs.exists }}
      n8n_tag: ${{ steps.find_tag.outputs.n8n_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Get GHCR token
        id: ghcr_token
        run: |
          GHCR_TOKEN=$(curl -s -u "mainto:${{ secrets.CR_PAT }}" \
            "https://ghcr.io/token?service=ghcr.io&scope=repository:n8n-io/n8n:pull" \
            | jq -r .token)
          echo "GHCR_TOKEN=$GHCR_TOKEN" >> $GITHUB_ENV
          half_len=$(( ${#GHCR_TOKEN} / 2 ))
          echo "GHCR_TOKEN_PARTS=${GHCR_TOKEN:0:$half_len}.${GHCR_TOKEN:$half_len}"

      - name: Get latest n8n tag and digest
        id: get_latest_tag_and_digest
        env:
          GHCR_TOKEN: ${{ env.GHCR_TOKEN }}
        run: |
          tags=$(curl -s -H "Authorization: Bearer $GHCR_TOKEN" \
            "https://ghcr.io/v2/n8n-io/n8n/tags/list" | jq -r '.tags[]' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -Vr)
          latest_tag=$(echo "$tags" | head -n 1)
          digest=$(curl -s -H "Authorization: Bearer $GHCR_TOKEN" \
            "https://ghcr.io/v2/n8n-io/n8n/manifests/$latest_tag" | jq -r .config.digest)
          echo "n8n_tag=$latest_tag" >> "$GITHUB_OUTPUT"
          echo "digest=$digest" >> "$GITHUB_OUTPUT"

      - name: Check if tag exists on GHCR
        id: tag_exists
        run: |
          TAG=${{ steps.find_tag.outputs.n8n_tag }}
          # 1. Get a pull-token for this repo
          GHCR_TOKEN=$(curl -s -u "mainto:${{ secrets.CR_PAT }}" \
            "https://ghcr.io/token?service=ghcr.io&scope=repository:${{ github.repository }}:pull" \
            | jq -r .token)

          # 2. Query the manifest using that token
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json" \
            -H "Authorization: Bearer $GHCR_TOKEN" \
            https://ghcr.io/v2/${{ github.repository }}/manifests/$TAG)
          echo "status=$STATUS"
          if [ "$STATUS" -eq 200 ]; then
            echo "exists=true"  >> "$GITHUB_OUTPUT"
          elif [ "$STATUS" -eq 403 ]; then
            exit 1 # Unauthorized
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.exists == 'false' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_build == 'true')
    steps:
      - uses: actions/checkout@v4

      - name: Print exists and tag
        run: |
          echo "Image exists: ${{ needs.check.outputs.exists }}"
          echo "n8n tag: ${{ needs.check.outputs.n8n_tag }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mainto
          password: ${{ secrets.CR_PAT }}

      - name: Build & push custom n8n
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ needs.check.outputs.n8n_tag }}
            ghcr.io/${{ github.repository }}:latest
